# -*- coding: utf-8 -*-
"""CNNYOLOV8INTEGRATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eoUiARcWrVIjcNcFPiig3skqhVfQpWsz
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics

import ultralytics
from tensorflow.keras.models import load_model
from ultralytics import YOLO
import matplotlib.pyplot as plt
import os
import random
import numpy as np
import cv2

# Load the ResNet50 classifier
cnn_model = load_model("/content/drive/MyDrive/YOLOV8/col_models/resnet50_pothole_model.h5")

# Load YOLOv8 trained model
yolo_model = YOLO("/content/drive/MyDrive/YOLOV8/col_models/yolov8_pothole_best.pt")

# Function to preprocess image for ResNet50
def preprocess_for_cnn(img_path, target_size=(224, 224)):
    img = cv2.imread(img_path)
    img_resized = cv2.resize(img, target_size)
    img_normalized = img_resized / 255.0
    return np.expand_dims(img_normalized, axis=0), img  # return both preprocessed and original image

# Function to predict and detect
def classify_and_detect(img_path):
    img_preprocessed, original_img = preprocess_for_cnn(img_path)

    # Predict using CNN
    pred = cnn_model.predict(img_preprocessed)
    predicted_class = np.argmax(pred)
    confidence = pred[0][predicted_class]

    print(f"🔍 CNN Prediction: {'Pothole' if predicted_class == 1 else 'Plain Road'} ({confidence:.2f})")

    if predicted_class == 1:
        # YOLOv8 Detection
        results = yolo_model.predict(source=img_path, conf=0.5, save=False, show=True)  # `show=True` to visualize in Colab
        results[0].show()  # For inline display in notebook
    else:
        # Just display the original image
        plt.imshow(cv2.cvtColor(original_img, cv2.COLOR_BGR2RGB))
        plt.title("Plain Road - No Detection")
        plt.axis("off")
        plt.show()

# Set path to your test images folder
test_images_dir = "/content/drive/MyDrive/YOLOV8/test_images"

# List all image files (jpg/png)
test_image_files = [f for f in os.listdir(test_images_dir) if f.endswith((".jpg", ".png"))]

# Pick a random image
random_image = random.choice(test_image_files)
test_img_path = os.path.join(test_images_dir, random_image)

print(f"🖼️ Randomly selected image: {test_img_path}")

# Pass through ResNet50 and YOLOv8 pipeline
classify_and_detect(test_img_path)