# -*- coding: utf-8 -*-
"""R+YOLOV8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v8sBygF6Lm3I8_zFL4mrvsTVY_AxTfKM
"""

import os
import numpy as np
import cv2
from sklearn.model_selection import train_test_split

from google.colab import drive
drive.mount('/content/drive')

# Update these paths as needed
plain_road_path = "/content/drive/MyDrive/YOLOV8/plain"
pothole_road_path = "/content/drive/MyDrive/YOLOV8/potholes"

# Load all plain road image paths
plain_images = sorted(os.listdir(plain_road_path))
plain_images = [os.path.join(plain_road_path, img) for img in plain_images if img.endswith(('.jpg', '.jpeg', '.png'))]

# Load first pothole image paths (no label check)
pothole_images = sorted([f for f in os.listdir(pothole_road_path) if f.endswith(('.jpg', '.jpeg', '.png'))])
pothole_images = [os.path.join(pothole_road_path, img) for img in pothole_images]

print(f"✅ Loaded {len(plain_images)} plain road images")
print(f"✅ Loaded {len(pothole_images)} pothole road images")

# Function to preprocess an image
def preprocess_image(img_path, target_size=(224, 224)):
    img = cv2.imread(img_path)
    img = cv2.resize(img, target_size)
    img = img / 255.0  # Normalize pixel values
    return img

import matplotlib.pyplot as plt
import cv2

# Provide the path to your image
image_path = '/content/drive/MyDrive/YOLOV8/potholes/potholes598_png_jpg.rf.201f0d1b2bdfbe976abf31dfab608ffc.jpg'  # Replace with actual image path

# Preprocess and display the image
processed_img = preprocess_image(image_path)

# Convert BGR (OpenCV default) to RGB for proper color display
processed_img_rgb = cv2.cvtColor((processed_img * 255).astype('uint8'), cv2.COLOR_BGR2RGB)

# Plot the image
plt.imshow(processed_img_rgb)
plt.title('Resized Image')
plt.axis('off')
plt.show()

# Lists to hold all preprocessed images
images = []
labels = []

# --- Preprocess plain road images (label = 0)
for img_path in plain_images:
    processed = preprocess_image(img_path)
    images.append(processed)
    labels.append(0)

# --- Preprocess first 1500 pothole images (label = 1)
for img_path in pothole_images:
    processed = preprocess_image(img_path)
    images.append(processed)
    labels.append(1)

# Convert to NumPy arrays
images = np.array(images)
labels = np.array(labels)

# Print result
print(f"✅ Total preprocessed images: {images.shape}")
print(f"✅ Corresponding labels: {labels.shape}")

import matplotlib.pyplot as plt
import numpy as np

# Show 6 random images with their label numbers and meanings
plt.figure(figsize=(12, 6))

for i in range(6):
    index = np.random.randint(0, len(images))  # Random index
    img = images[index]
    label = labels[index]

    plt.subplot(2, 3, i + 1)
    plt.imshow(img)
    plt.title(f"Label: {label} - {'Plain Road' if label == 0 else 'Pothole'}")
    plt.axis("off")

plt.tight_layout()
plt.show()

X_train, X_test, y_train, y_test = train_test_split(
    images, labels, test_size=0.2, random_state=42, shuffle=True
)

# Print shapes to verify
print(f"✅ Training set shape: {X_train.shape}, Labels: {y_train.shape}")
print(f"✅ Test set shape: {X_test.shape}, Labels: {y_test.shape}")

from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical

y_train_cat = to_categorical(y_train, num_classes=2)
y_test_cat = to_categorical(y_test, num_classes=2)

import numpy as np

# Print 5 random samples from y_train and y_train_cat
print("🔍 Sample original vs. one-hot encoded labels:\n")

for i in range(5):
    index = np.random.randint(0, len(y_train))
    original_label = y_train[index]
    one_hot_label = y_train_cat[index]
    print(f"Index {index} → Original: {original_label} → One-Hot: {one_hot_label}")

base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

# Unfreeze the base model
base_model.trainable = True

# Freeze all layers except the last 20
for layer in base_model.layers[:-20]:
    layer.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.3)(x)
x = Dense(64, activation='relu')(x)
predictions = Dense(2, activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=predictions)

model.compile(optimizer=Adam(learning_rate=1e-4),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(X_train, y_train_cat,
                    validation_data=(X_test, y_test_cat),
                    epochs=30,
                    batch_size=32,
                    verbose = 1 )

loss, accuracy = model.evaluate(X_test, y_test_cat)
print(f"✅ Test Accuracy: {accuracy*100:.2f}%")

model.save("resnet50_pothole_classifier.h5")

model.save('/content/drive/MyDrive/YOLOV8/col_models/resnet50_pothole_model.h5')

import matplotlib.pyplot as plt
import numpy as np

# Choose a random index from the test set
index = np.random.randint(0, len(X_test))
img = X_test[index]
true_label = y_test[index]

# Expand dims to match model input shape: (1, 224, 224, 3)
input_img = np.expand_dims(img, axis=0)

# Predict using trained ResNet50 model
pred_probs = model.predict(input_img)  # Output: [[0.98, 0.02]]
pred_label = np.argmax(pred_probs)

# Label names
label_names = ["Plain Road", "Pothole"]

# Display image with labels
plt.imshow(img)
plt.axis('off')
plt.title(f"True: {label_names[true_label]} | Predicted: {label_names[pred_label]}")
plt.show()

!pip install ultralytics

!pip install ultralytics
from ultralytics import YOLO

from ultralytics import YOLO

model = YOLO("yolov8n.yaml")

model.train(data="/content/drive/MyDrive/YOLOV8/data.yaml",
            epochs=100,
            imgsz=640,
            batch=16,
            project="pothole_yolo_default",
            name="yolov8n")

!cp /content/pothole_yolo_default/yolov8n2/weights/best.pt /content/drive/MyDrive/YOLOV8/col_models/yolov8_pothole_best.pt

!ls /content/pothole_yolo_default/yolov8n22/weights

metrics = model.val()

print("📊 Final YOLOv8 Detection Accuracy Report")
print("------------------------------------------")
print(f"mAP@0.5:         {metrics.box.map50:.4f} ({metrics.box.map50 * 100:.2f}%)")
print(f"mAP@0.5:0.95:    {metrics.box.map:.4f} ({metrics.box.map * 100:.2f}%)")
print(f"Precision:       {metrics.box.mp:.4f} ({metrics.box.mp * 100:.2f}%)")
print(f"Recall:          {metrics.box.mr:.4f} ({metrics.box.mr * 100:.2f}%)")

import os

def find_best_pt():
    best_paths = []
    for root, dirs, files in os.walk("/"):
        for file in files:
            if file == "best.pt":
                best_paths.append(os.path.join(root, file))
    return best_paths

# Run the search
paths = find_best_pt()

# Display results
if paths:
    print("✅ Found best.pt file(s):")
    for path in paths:
        print(path)
else:
    print("❌ No best.pt file found in the file system.")

from ultralytics import YOLO
import random
import os

# Load your trained model
model = YOLO("/content/pothole_yolo_default/yolov8n2/weights/best.pt")

# Choose a random image from validation set
val_img_dir = "/content/drive/MyDrive/YOLOV8/dataset/images/val"
random_img = random.choice([f for f in os.listdir(val_img_dir) if f.endswith(('.jpg', '.png'))])
random_img_path = os.path.join(val_img_dir, random_img)

print(f"Running inference on: {random_img_path}")

# Run prediction
results = model.predict(source=random_img_path, conf=0.3)

# Show the image with predicted bounding boxes
results[0].show()

from ultralytics import YOLO

# Load the trained model
model = YOLO("/content/pothole_yolo_default/yolov8n_15002/weights/best.pt")

# Evaluate on validation data (defined in your data.yaml)
metrics = model.val()

# Print mAP and other evaluation metrics
print(metrics)